version: "3"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    environment:
      DB_NAME: datagov
      DB_USER: root
      DB_PASSWORD: mysql-dev-password
      DB_HOST: db
      WP_CONTENT_PROTOCOL: http
      WP_ENV: development

      # Development non-secrets
      AUTH_KEY: test-auth-key
      AUTH_SALT: test-auth-salt
      LOGGED_IN_KEY: test-logged-in-key
      LOGGED_IN_SALT: test-logged-in-salt
      NONCE_KEY: test-nonce-key
      NONCE_SALT: test-nonce-salt
      SECURE_AUTH_KEY: test-secure-auth-eky
      SECURE_AUTH_SALT: test-secure-auth-salt
    ports:
      - "9000"
    volumes:
      - .:/var/www
      - composer:/var/www/vendor

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mysql-dev-password
      MYSQL_DATABASE: datagov
    ports:
      - "3306"
    volumes:
      - db:/var/lib/mysql

  nginx:
    image: nginx
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  db:
  composer:
