---
version: "3"
services:
  app:
    volumes:
      - www:/var/www
  nginx:
    volumes:
      - www:/var/www
  test:
    build:
      context: .
      dockerfile: docker/Dockerfile.test
    depends_on:
      - nginx

volumes:
  www:
