version: "3"
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    depends_on:
      - db
    environment:
      WP_ENV: development
      WP_HOME: http://localhost:8000
      WP_SITEURL: http://localhost:8000/wp
      DB_NAME: datagov
      DB_USER: root
      DB_PASSWORD: mysql-dev-password
      DB_HOST: db
    ports:
      - "9000"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mysql-dev-password
      MYSQL_DATABASE: datagov
    ports:
      - "3306"
    volumes:
      - db:/var/lib/mysql

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - app

volumes:
  db:
