---
version: 2
jobs:
  build:
    docker:
      - image: circleci/php
    steps:
      - checkout
      - setup_remote_docker
      - run: make build
      - run: make configure
      - run: make test


workflows:
  version: 2
  commit:
    jobs:
      - build
