---
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build the application image
          command: make build
      - run:
          name: Start the application
          command: make up
      - run:
          name: Clean running application
          command: docker-compose down -v

  deploy-sandbox:
    docker:
      - image: circleci/python:3.6
    environment:
      JENKINS_URL: https://ci.sandbox.datagov.us
    steps:
      - checkout
      - deploy:
          name: jenkins
          command: ./jenkins_build deploy-ci-app-wordpress


workflows:
  version: 2
  commit:
    jobs:
      - build
      - deploy-sandbox:
          requires:
            - build
          filters:
            branches:
              only: master

  weekly:
    triggers:
      - schedule:
          cron: "0 4 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
