---
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-jessie-node
    steps:
      - checkout
      - run: sudo apt install -y subversion
      - restore_cache:
          keys:
            - v1-composer-{{ checksum "composer.lock" }}
            - v1-composer-
      - run:
          name: Build the application image
          command: make build
      - run:
          name: Start the application
          command: make up
      - run:
          name: Install app plugins
          command: make setup
      - save_cache:
          key: v1-composer-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run: sudo npm install -g snyk
      - run: snyk test

  deploy-sandbox:
    docker:
      - image: circleci/python:3.6
    environment:
      JENKINS_URL: https://ci.sandbox.datagov.us
    steps:
      - checkout
      - deploy:
          name: jenkins
          command: ./jenkins_build deploy-ci-app-wordpress


workflows:
  version: 2
  commit:
    jobs:
      - build
      - deploy-sandbox:
          requires:
            - build
          filters:
            branches:
              only: master

  weekly:
    triggers:
      - schedule:
          cron: "0 4 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
